### ISSUE TITLE
Assignment-1 10174102126

### ISSUE THREAD

**Issue by xiaoyujinghe** [X-lab2017/22-Spring-OSDD#1]
何雨菁的issues

**Comment by TieWay59** [comment]
您好！    您的来信已收到，我会尽快给您回复！    顺颂商祺！

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156109646-cf4fdd0d-9f1a-4b55-8935-98979f3df5e7.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156109916-b6030fb5-37b8-4c11-9e3f-6e0c72c75d31.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156110176-32c372f5-4a73-4273-ac3a-e0ab703988e1.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156110615-34a3c7b5-bbde-4c6a-a764-f1435a8ba74d.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156111086-e800aba9-cdcc-4dcb-b692-72651aa1acaa.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156111362-7438082f-4011-4627-86d9-ce3937749ec3.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156112799-be513429-fb59-4601-a8a3-2e83b26cbd32.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156113997-4fbe8d67-c797-4a37-bc8b-4ebf45bb127e.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156114327-0d8b078c-6103-42c8-81b8-f442d3e3291e.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156115096-0bd5a04b-0c64-4675-84ae-cddaabd3124b.png)

**Comment by xiaoyujinghe** [comment]
![image](https://user-images.githubusercontent.com/53068665/156115193-cdd9375e-da89-4370-817f-1cdfda768bc6.png)
